### ISSUE TITLE
[BUG] Spectrum crashes after loading the world on a dedicated server

### ISSUE THREAD

**Issue by Telmud** [DaFuqs/Spectrum#289] opened 2023-12-07 15:19 UTC
**Describe the bug**
Spectrum crashes right after loading the world on a dedicated server. The mod crashes trying to "inject additional recipes". I'm running the server on Ubuntu 22.04.3 LTS on version 1.20.1 with loader 0.15.0. Crash report is down below. I'm also attaching [latest.log](https://github.com/DaFuqs/Spectrum/files/13601766/latest.log). Maybe this has something to do with this [commit](https://github.com/DaFuqs/Spectrum/commit/123dfbf099e0b1b9e7924cf78038ac42b8a7309f). The issue does not happen while launching single player world on different hardware.

**To Reproduce**
1. Start the server
2. Let the server load in the world.
3. Server immediately crashes.

**Expected behavior**
1. Start the server
2. Let the server load in the world.
3. Server does not immediately crash.

**Mod version**
spectrum-1.7.1-deeper-down.jar
Minecraft 1.20.1
Fabric Loader 0.15.0

**Screenshots**
No screenshots needed.

**Crash Report**
```---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-12-07 14:35:28
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_310
	at de.dafuqs.spectrum.blocks.idols.FirestarterIdolBlock.addBlockSmeltingRecipes(FirestarterIdolBlock.java:47)
	at de.dafuqs.spectrum.SpectrumCommon.lambda$onInitialize$9(SpectrumCommon.java:327)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$zea000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2842)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-89-generic
	Java Version: 17.0.9, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 332789768 bytes (317 MiB) / 1000341504 bytes (954 MiB) up to 1000341504 bytes (954 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Pentium(R) Dual-Core  CPU      E5800  @ 3.20GHz
	Identifier: Intel64 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: 4 Series Chipset Integrated Graphics Controller
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x2e32
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5709.34
	Virtual memory used (MB): 1761.58
	Swap memory total (MB): 3804.00
	Swap memory used (MB): 0.75
	JVM Flags: 0 total; 
	Fabric Mods: 
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.0
			mixinextras: MixinExtras 0.3.0
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		patchouli: Patchouli 1.20.1-83-FABRIC
			fiber: fiber 0.23.0-2
		revelationary: Revelationary 1.3.5+1.20.1
		spectrum: Spectrum 1.7.1
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			arrowhead: Arrowhead 1.2.0-1.19.4
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			cardinal-components-level: Cardinal Components API (world saves) 5.2.1
			fractal: Fractal 1.0.0
			incubus_core: Incubus Core 1.8.4
			org_jgrapht_jgrapht-core: jgrapht-core 1.5.1
			org_jheaps_jheaps: jheaps 0.13
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			reverb: Reverb 1.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		trinkets: Trinkets 3.7.1
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Noaaan** [comment] 2023-12-07 15:38
Very nice and tidy issue. I believe this is a duplicate of https://github.com/DaFuqs/Spectrum/issues/287, which the fix is scheduled for next release

**Comment by Telmud** [comment] 2023-12-07 17:44
Just out of curiousity I've built spectrum from source using 1.20.1 branch and this time it appears to load in using previous configuration

**Closed as completed** 2023-12-07 19:17 UTC
Labels: bug, duplicate, awaiting_release
