### ISSUE TITLE
[BUG] crash about missing layer definitions while using sinytra connector and forge

### ISSUE THREAD

**Issue by AceTheWildCard** [DaFuqs/Spectrum#414] opened 2024-06-10 16:19 UTC
**Describe the bug**
unsure if its my graphics driver or something that updated, but i get a crash report now. ive tried downgrading mods, updating mods, removing mods, readding mods. nothing seems to work...

**To Reproduce**
hitting play on the launcher and waiting for the game to load

**Expected behavior**
game to load to title screen

**Minecraft version**
1.20.1 forge

**Mod version**
1.7.7

**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here
[crash-2024-06-10_11.59.19-client.txt](https://github.com/user-attachments/files/15776192/crash-2024-06-10_11.59.19-client.txt)

**Comment by AceTheWildCard** [comment] 2024-06-10 16:19
was unsure if i should post this here or on the siyntra connector github

**Comment by AceTheWildCard** [comment] 2024-06-12 14:22
after reading some of the other bug reports i may have found the problem, i upgraded spectrum to 1.7.8 and downgraded enchantment discriptions to 17.0.15, and that seems to have fixed it. i AM still using forge though. so it seems enchantment descriptions might not be cooperating with spectrum.

**Comment by DaFuqs** [comment] 2024-06-13 15:19
They changed their internal code, so the changes Spectrum wants to make fail.
This will be fixed in the next update via https://github.com/DaFuqs/Spectrum/commit/5584cce30cc84805add2e9a2c04790cfb3d3a827

**Comment by DaFuqs** [comment] 2024-06-13 20:14
Since the issue is a duplicate to #411, I will close this one, but keep the other one open until the release is out.
Ty for looking into this!

**Closed as completed by DaFuqs** 2024-06-13 20:14 UTC
Labels: bug
