### ISSUE TITLE
[BUG] Doomblooms are unfarmable / We need primordial fire immunity

### ISSUE THREAD

**Issue by Azzyypaaras** [DaFuqs/Spectrum#281] opened 2023-11-22 05:07 UTC
**Describe the bug**
When we created primordial fire, we really didn't stop and think about stuff that should be immune to it. It made enough sense at a time since the answer is that nothing should be but uh. Well.

Doomblooms spread their seeds by exploding. This explosion creates a raging inferno of... primordial fire...

...which the seeds are right in the middle off. And which they are not immune to.

**To Reproduce**
Grow a doombloom, blow it up, and watch as the seeds you worked so hard for are consume by the raging rancor of their mother.

**Suggestion Going Forward**
We should set up a system to mark certain items as immune to primordial fire. Additionally, we should probably make a tag for immunity as well.

**Mod version**
1.7.0

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/20349662/ba88d94a-55d6-4e9a-9b2d-f966e6b07656)

**Notes**
You know, annoying as this may be I am quite pleased to see this be the only issue with PF so far.

**Comment by DaFuqs** [comment] 2023-11-22 06:56
What a nice bug report. This one will be fun. Soooo:

- I can confirm the bug in the final release
- Alpha versions do not seem to have that issue. I could throw Doombloom Seeds into Primordial Fire without them burning up no problem.

=> It looks like the issue was introduced right at release. Smh no proper testing. Lazy modders.

Good thing Spectrum has a system in place to make certain items immune to specific forms of damage: 
https://github.com/DaFuqs/Spectrum/blob/c26bf40596a37595c12f1b90ec80fdb449a0974f/src/main/java/de/dafuqs/spectrum/registries/SpectrumItemStackDamageImmunities.java#L31

But wait... Doombloom seeds are marked to be immune to being on fire. So since items with "on fire" immunity have their item entities marked as fireproof 
https://github.com/DaFuqs/Spectrum/blob/c26bf40596a37595c12f1b90ec80fdb449a0974f/src/main/java/de/dafuqs/spectrum/mixin/ItemEntityMixin.java#L157
 they totally should not burn up in primordial fire, right?

Someone must have made stuff immune to fire still take damage by primordial fire. Who could it have been?? I's a mystery 🤔 🤔 🤔

**Comment by DaFuqs** [comment] 2023-12-06 18:46
Skill issued ✅

**Closed as completed by DaFuqs** 2023-12-06 18:46 UTC
Labels: bug, enhancement, skill_issue
