### ISSUE TITLE
[BUG] Fusion Crafter multiblock completely erased/bugged the surrounding chunks

### ISSUE THREAD

**Issue by DaemonSzym** [DaFuqs/Spectrum#124] opened 2022-10-15 19:57 UTC
The bug happened after I constructed the Fusion Crafter multiblock in MC All of fabric 5, on a friends server. The bug happened after I logged out, having put in the materials for making onyx. When i logged back in, half my base was invisible but interactable, while the specific chunk on the fusion crafter was intangible but the particles still existed. The server then crashed, and I was no longer able to log in.

Create the fusion crafter multiblock in all of fabric 5, put in materials for onyx, log off. Log in.

Invisible surrounding chunks of the fusion crafter, fusion crafter chunk itself invisible and non-interactable.

Version 1.5.0

No crash report was generated

**Comment by Noaaan** [comment] 2022-10-15 20:57
This is a duplicate of #118, and has already been fixed in the later versions of Spectrum

**Comment by DaFuqs** [comment] 2022-10-16 09:15
What he says. A client update tp 1.5.2 will suffice 👌

**Closed as completed by DaFuqs** 2022-10-16 09:15 UTC
Labels: bug

**Comment by DaemonSzym** [comment] 2022-10-16 11:02
Thanks! I tried to look for the issue but Im new to github so I couldnt find anything.
