### ISSUE TITLE
[BUG] Spectrum book error

### ISSUE THREAD

**Issue by P1agueDoc** [DaFuqs/Spectrum#194] opened 2023-06-03 11:07 UTC
**Describe the bug**
I created a server for my friends. When they open book from spectrum (colorfull world) they get error (screnshot). When playing in singleplayer there's no such problem, all works fine.
**To Reproduce**
just open book

**Expected behavior**
Normal book
**Mod version**
Lates release version for 1.19.2 fabric (not new alpha)

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/46785308/adf875c0-e85d-4a2e-a979-88a08e556fbc)
(Writed in green - check the log file for more information)

**Crash Report**
game doesn't crash or anything, just book does't work.
Added: I can open this book and everything works fine (im hosting on another computer in my house), book doesn't works for others.
Whe play on mod pack all of fabric 6

**Comment by DaFuqs** [comment] 2023-06-03 12:29
Caused by the outdated russian-language guidebook, sorry! I'll correct that for the next update.
In the meantime, if the game is set to english when starting up the guidebook should work as normal.

**Comment by P1agueDoc** [comment] 2023-06-03 12:35
Thanks

**Comment by DaFuqs** [comment] 2023-06-18 18:15
Fixed in Spectrum 1.6.11-1.19.2-leisure_time

**Closed as completed by DaFuqs** 2023-06-18 18:15 UTC
Labels: bug, awaiting_release

**Comment by Mosklia** [comment] 2023-07-04 12:59
The same thing happened on Simplified Chinese. My mod version is 1.19.2-deeper-down-alpha-16, and Patchouli Book says `Unknown item ID: spectrum:mermaids_brush`.

**Comment by DaFuqs** [comment] 2023-07-04 15:40
> The same thing happened on Simplified Chinese. My mod version is 1.19.2-deeper-down-alpha-16, and Patchouli Book says `Unknown item ID: spectrum:mermaids_brush`.

Will fix with the next alpha, ty!
