### ISSUE TITLE
Experiment #1 completed - No progression

### ISSUE THREAD

**Issue by LexsiJ** [DaFuqs/Spectrum#177] opened 2023-03-29 00:31 UTC
**Describe the bug**
Completed Experiment #1 (have 35 of the output item in inventory - completed this many times)
Have been completing everything I could to move past - onyx completed even
Still stuck - so I 'purchased' the concise instructions.....tells me to do what I've already done many times
So...I do it again - still stuck

**To Reproduce**
complete experiment #1 without progressing

**Expected behavior**
explained in describe bug

**Mod version**
spectrum-1.6.9-1.19.2-leisure_time.jar

**Screenshots**
![image](https://user-images.githubusercontent.com/42349498/228396289-7ef252d1-4166-4a77-8210-87dd00121182.png)
![image](https://user-images.githubusercontent.com/42349498/228396320-f5006914-3ef0-4403-bc31-443f15fde791.png)
![image](https://user-images.githubusercontent.com/42349498/228396358-6162da3e-0583-4413-a939-13c0a0e86617.png)

**Crash Report**
If it is a crash bug add your crash log here

**Comment by Shoes4Clues** [comment] 2023-03-30 21:31
Have you been breaking the Magical Leaves variant of the block? That may be the cause of your issue, as it might be checking to see if you break the normal leaves variant.

**Comment by ghost** [comment] 2023-04-01 02:28
I have the same issue with this, have you found a solution ?

**Comment by DaFuqs** [comment] 2023-04-05 07:04
> So...I do it again - still stuck

I am a bit confused where you are stuck here, sorry. Reading that you have reached Onyx, you sucessfully completed that step and reached the end of advancement tree nr 1.
Do you mean the book entry about experiment 1 is still marked as incomplete, the advancement not unlocked, ...?

**Comment by LexsiJ** [comment] 2023-04-14 17:35
The issue was the experiment kept the indicator of need to do in the book, even after completing it and the next.

**Comment by DaFuqs** [comment] 2023-09-28 07:29
Fixed in Spectrum's alpha builds.

**Closed as completed by DaFuqs** 2023-09-28 07:29 UTC
Labels: bug, awaiting_release
